<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cca.event_bindings.image.subscriber' shared service.

return $this->services['cca.event_bindings.image.subscriber'] = new \ContaoCommunityAlliance\Contao\Bindings\Subscribers\ImageSubscriber(${($_ = isset($this->services['contao.framework']) ? $this->services['contao.framework'] : $this->getContao_FrameworkService()) && false ?: '_'}, ${($_ = isset($this->services['contao.image.image_factory']) ? $this->services['contao.image.image_factory'] : $this->load('getContao_Image_ImageFactoryService.php')) && false ?: '_'}, $this->targetDirs[3]);
