<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.cache.warm_internal' shared service.

return $this->services['contao.cache.warm_internal'] = new \Contao\CoreBundle\Cache\ContaoCacheWarmer(${($_ = isset($this->services['filesystem']) ? $this->services['filesystem'] : ($this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem())) && false ?: '_'}, ${($_ = isset($this->services['contao.resource_finder']) ? $this->services['contao.resource_finder'] : $this->load('getContao_ResourceFinderService.php')) && false ?: '_'}, ${($_ = isset($this->services['contao.resource_locator']) ? $this->services['contao.resource_locator'] : $this->load('getContao_ResourceLocatorService.php')) && false ?: '_'}, $this->targetDirs[3], ${($_ = isset($this->services['doctrine.dbal.default_connection']) ? $this->services['doctrine.dbal.default_connection'] : $this->getDoctrine_Dbal_DefaultConnectionService()) && false ?: '_'}, ${($_ = isset($this->services['contao.framework']) ? $this->services['contao.framework'] : $this->getContao_FrameworkService()) && false ?: '_'});
