<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao_manager.routing_loader' shared service.

return $this->services['contao_manager.routing_loader'] = new \Contao\ManagerBundle\Routing\RouteLoader(${($_ = isset($this->services['routing.loader']) ? $this->services['routing.loader'] : $this->load('getRouting_LoaderService.php')) && false ?: '_'}, ${($_ = isset($this->services['contao_manager.plugin_loader']) ? $this->services['contao_manager.plugin_loader'] : $this->get('contao_manager.plugin_loader', 1)) && false ?: '_'}, ${($_ = isset($this->services['kernel']) ? $this->services['kernel'] : $this->get('kernel', 1)) && false ?: '_'});
