<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.menu.matcher' shared service.

return $this->services['contao.menu.matcher'] = new \Knp\Menu\Matcher\Matcher();
