<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao_bootstrap.core.listener.module_dca' shared service.

return $this->services['contao_bootstrap.core.listener.module_dca'] = new \ContaoBootstrap\Core\Listener\Dca\ModuleDcaListener();
