<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.image.resize_calculator' shared service.

return $this->services['contao.image.resize_calculator'] = new \Contao\Image\ResizeCalculator();
