<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.menu.renderer' shared service.

return $this->services['contao.menu.renderer'] = new \Knp\Menu\Renderer\ListRenderer(${($_ = isset($this->services['contao.menu.matcher']) ? $this->services['contao.menu.matcher'] : ($this->services['contao.menu.matcher'] = new \Knp\Menu\Matcher\Matcher())) && false ?: '_'});
