<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.installer' shared service.

return $this->services['contao.installer'] = new \Contao\InstallationBundle\Database\Installer(${($_ = isset($this->services['doctrine.dbal.default_connection']) ? $this->services['doctrine.dbal.default_connection'] : $this->getDoctrine_Dbal_DefaultConnectionService()) && false ?: '_'}, ${($_ = isset($this->services['contao.doctrine.schema_provider']) ? $this->services['contao.doctrine.schema_provider'] : $this->getContao_Doctrine_SchemaProviderService()) && false ?: '_'});
