<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ctn.materialiconsinserttag.listener.hooks' shared service.

return $this->services['ctn.materialiconsinserttag.listener.hooks'] = new \ContaoThemesNet\MaterialIconsInserttag\EventListener\HookListener(${($_ = isset($this->services['contao.framework']) ? $this->services['contao.framework'] : $this->getContao_FrameworkService()) && false ?: '_'});
