<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.listener.exception_converter' shared service.

return $this->services['contao.listener.exception_converter'] = new \Contao\CoreBundle\EventListener\ExceptionConverterListener();
