<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao_bootstrap.grid.grid_provider' shared service.

return $this->services['contao_bootstrap.grid.grid_provider'] = new \ContaoBootstrap\Grid\GridProvider(${($_ = isset($this->services['contao_bootstrap.grid.grid_builder']) ? $this->services['contao_bootstrap.grid.grid_builder'] : ($this->services['contao_bootstrap.grid.grid_builder'] = new \ContaoBootstrap\Grid\GridBuilder())) && false ?: '_'});
