<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.image.imagine_svg' shared service.

return $this->services['contao.image.imagine_svg'] = new \Contao\ImagineSvg\Imagine();
