<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cca.event_bindings.system.subscriber' shared service.

return $this->services['cca.event_bindings.system.subscriber'] = new \ContaoCommunityAlliance\Contao\Bindings\Subscribers\SystemSubscriber(${($_ = isset($this->services['contao.framework']) ? $this->services['contao.framework'] : $this->getContao_FrameworkService()) && false ?: '_'}, ${($_ = isset($this->services['monolog.logger.contao']) ? $this->services['monolog.logger.contao'] : $this->load('getMonolog_Logger_ContaoService.php')) && false ?: '_'});
