<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.data_collector' shared service.

$this->services['contao.data_collector'] = $instance = new \Contao\CoreBundle\DataCollector\ContaoDataCollector($this->parameters['kernel.packages']);

$instance->setFramework(${($_ = isset($this->services['contao.framework']) ? $this->services['contao.framework'] : $this->getContao_FrameworkService()) && false ?: '_'});

return $instance;
