<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao_manager.listener.install_command' shared service.

return $this->services['contao_manager.listener.install_command'] = new \Contao\ManagerBundle\EventListener\InstallCommandListener(($this->targetDirs[3].'/app/..'));
