<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao_bootstrap.grid.listeners.theme_import' shared service.

return $this->services['contao_bootstrap.grid.listeners.theme_import'] = new \ContaoBootstrap\Grid\Listener\ThemeImportListener();
