<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao_bootstrap.config' shared service.

return $this->services['contao_bootstrap.config'] = new \ContaoBootstrap\Core\Config\ArrayConfig($this->parameters['contao_bootstrap.config']);
