<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.image.resizer' shared service.

$this->services['contao.image.resizer'] = $instance = new \Contao\CoreBundle\Image\LegacyResizer(($this->targetDirs[3].'/assets/images'), ${($_ = isset($this->services['contao.image.resize_calculator']) ? $this->services['contao.image.resize_calculator'] : ($this->services['contao.image.resize_calculator'] = new \Contao\Image\ResizeCalculator())) && false ?: '_'}, ${($_ = isset($this->services['filesystem']) ? $this->services['filesystem'] : ($this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem())) && false ?: '_'});

$instance->setFramework(${($_ = isset($this->services['contao.framework']) ? $this->services['contao.framework'] : $this->getContao_FrameworkService()) && false ?: '_'});

return $instance;
