<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao_bootstrap.core.listener.parse_template' shared service.

return $this->services['contao_bootstrap.core.listener.parse_template'] = new \ContaoBootstrap\Core\Listener\TemplateParseListener(${($_ = isset($this->services['contao_bootstrap.view.template.pre_render_filter']) ? $this->services['contao_bootstrap.view.template.pre_render_filter'] : ($this->services['contao_bootstrap.view.template.pre_render_filter'] = new \ContaoBootstrap\Core\View\Template\Filter\TemplatePreRenderFilter([]))) && false ?: '_'}, ${($_ = isset($this->services['contao_bootstrap.view.template.post_render_filter']) ? $this->services['contao_bootstrap.view.template.post_render_filter'] : ($this->services['contao_bootstrap.view.template.post_render_filter'] = new \ContaoBootstrap\Core\View\Template\Filter\TemplatePostRenderFilter([]))) && false ?: '_'});
