<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao_bootstrap.core.config_subscriber' shared service.

return $this->services['contao_bootstrap.core.config_subscriber'] = new \ContaoBootstrap\Core\Listener\ConfigSubscriber(${($_ = isset($this->services['doctrine.dbal.default_connection']) ? $this->services['doctrine.dbal.default_connection'] : $this->getDoctrine_Dbal_DefaultConnectionService()) && false ?: '_'}, ${($_ = isset($this->services['contao_bootstrap.config']) ? $this->services['contao_bootstrap.config'] : $this->load('getContaoBootstrap_ConfigService.php')) && false ?: '_'});
