<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.command.symlinks' shared service.

return $this->services['contao.command.symlinks'] = new \Contao\CoreBundle\Command\SymlinksCommand($this->targetDirs[3], 'files', ($this->targetDirs[2].'/logs'), ${($_ = isset($this->services['contao.resource_finder']) ? $this->services['contao.resource_finder'] : $this->load('getContao_ResourceFinderService.php')) && false ?: '_'});
