<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cca.meta_palettes.parser' shared service.

return $this->services['cca.meta_palettes.parser'] = new \ContaoCommunityAlliance\MetaPalettes\Parser\MetaPaletteParser();
