<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.security.authenticator' shared service.

$this->services['contao.security.authenticator'] = $instance = new \Contao\CoreBundle\Security\ContaoAuthenticator(${($_ = isset($this->services['contao.routing.scope_matcher']) ? $this->services['contao.routing.scope_matcher'] : $this->getContao_Routing_ScopeMatcherService()) && false ?: '_'});

$instance->setContainer($this);

return $instance;
