<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.image.imagine' shared service.

return $this->services['contao.image.imagine'] = new \Imagine\Gd\Imagine();
