<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.resource_finder' shared service.

return $this->services['contao.resource_finder'] = new \Contao\CoreBundle\Config\ResourceFinder($this->getParameter('contao.resources_paths'));
