<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'MenAtWork\MultiColumnWizardBundle\EventListener\Mcw\ColorPicker' shared service.

return $this->services['MenAtWork\\MultiColumnWizardBundle\\EventListener\\Mcw\\ColorPicker'] = new \MenAtWork\MultiColumnWizardBundle\EventListener\Mcw\ColorPicker(${($_ = isset($this->services['contao.framework']) ? $this->services['contao.framework'] : $this->getContao_FrameworkService()) && false ?: '_'}->getAdapter("Contao\\Image"), ${($_ = isset($this->services['contao.framework']) ? $this->services['contao.framework'] : $this->getContao_FrameworkService()) && false ?: '_'}->getAdapter("Contao\\StringUtil"), ${($_ = isset($this->services['cca.translator.backport45translator']) ? $this->services['cca.translator.backport45translator'] : $this->getCca_Translator_Backport45translatorService()) && false ?: '_'});
