<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'cca.meta_palettes.listeners.meta_models_builders' shared service.

return $this->services['cca.meta_palettes.listeners.meta_models_builders'] = new \ContaoCommunityAlliance\MetaPalettes\Listener\MetaPalettesBuilder(${($_ = isset($this->services['contao.framework']) ? $this->services['contao.framework'] : $this->getContao_FrameworkService()) && false ?: '_'}, ${($_ = isset($this->services['cca.meta_palettes.parser']) ? $this->services['cca.meta_palettes.parser'] : ($this->services['cca.meta_palettes.parser'] = new \ContaoCommunityAlliance\MetaPalettes\Parser\MetaPaletteParser())) && false ?: '_'});
