<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao_bootstrap.view.template.pre_render_filter' shared service.

return $this->services['contao_bootstrap.view.template.pre_render_filter'] = new \ContaoBootstrap\Core\View\Template\Filter\TemplatePreRenderFilter([]);
