<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'cca.meta_palettes.listener.sub_select_palettes_listener' shared service.

return $this->services['cca.meta_palettes.listener.sub_select_palettes_listener'] = new \ContaoCommunityAlliance\MetaPalettes\Listener\SubSelectPalettesListener(${($_ = isset($this->services['doctrine.dbal.default_connection']) ? $this->services['doctrine.dbal.default_connection'] : $this->getDoctrine_Dbal_DefaultConnectionService()) && false ?: '_'});
