<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'MenAtWork\MultiColumnWizardBundle\EventListener\Mcw\DatePicker' shared service.

return $this->services['MenAtWork\\MultiColumnWizardBundle\\EventListener\\Mcw\\DatePicker'] = new \MenAtWork\MultiColumnWizardBundle\EventListener\Mcw\DatePicker();
