<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'MenAtWork\MultiColumnWizardBundle\EventListener\Contao\ExecutePostActions' shared service.

return $this->services['MenAtWork\\MultiColumnWizardBundle\\EventListener\\Contao\\ExecutePostActions'] = new \MenAtWork\MultiColumnWizardBundle\EventListener\Contao\ExecutePostActions(${($_ = isset($this->services['event_dispatcher']) ? $this->services['event_dispatcher'] : $this->getEventDispatcherService()) && false ?: '_'});
