<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Netzmacht\Contao\Toolkit\Dca\Listener\Save\GenerateAliasListener' shared service.

return $this->services['Netzmacht\\Contao\\Toolkit\\Dca\\Listener\\Save\\GenerateAliasListener'] = new \Netzmacht\Contao\Toolkit\Dca\Listener\Save\GenerateAliasListener($this, ${($_ = isset($this->services['netzmacht.contao_toolkit.dca.manager']) ? $this->services['netzmacht.contao_toolkit.dca.manager'] : $this->load('getNetzmacht_ContaoToolkit_Dca_ManagerService.php')) && false ?: '_'}, 'netzmacht.contao_toolkit.data.alias_generator.factory.default_factory');
