<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'monolog.logger.php' shared service.

$this->services['monolog.logger.php'] = $instance = new \Symfony\Bridge\Monolog\Logger('php');

$instance->pushProcessor(${($_ = isset($this->services['contao.monolog.processor']) ? $this->services['contao.monolog.processor'] : $this->getContao_Monolog_ProcessorService()) && false ?: '_'});
$instance->pushHandler(${($_ = isset($this->services['monolog.handler.console']) ? $this->services['monolog.handler.console'] : $this->getMonolog_Handler_ConsoleService()) && false ?: '_'});
$instance->pushHandler(${($_ = isset($this->services['monolog.handler.main']) ? $this->services['monolog.handler.main'] : $this->getMonolog_Handler_MainService()) && false ?: '_'});
$instance->pushHandler(${($_ = isset($this->services['contao.monolog.handler']) ? $this->services['contao.monolog.handler'] : $this->getContao_Monolog_HandlerService()) && false ?: '_'});

return $instance;
