<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'netzmacht.contao_toolkit.data.alias_generator.factory.default_factory' shared service.

return $this->services['netzmacht.contao_toolkit.data.alias_generator.factory.default_factory'] = new \Netzmacht\Contao\Toolkit\Data\Alias\Factory\ToolkitAliasGeneratorFactory(${($_ = isset($this->services['doctrine.dbal.default_connection']) ? $this->services['doctrine.dbal.default_connection'] : $this->getDoctrine_Dbal_DefaultConnectionService()) && false ?: '_'});
