<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'netzmacht.contao_toolkit.repository_manager' shared service.

return $this->services['netzmacht.contao_toolkit.repository_manager'] = new \Netzmacht\Contao\Toolkit\Data\Model\ToolkitRepositoryManager(${($_ = isset($this->services['doctrine.dbal.default_connection']) ? $this->services['doctrine.dbal.default_connection'] : $this->getDoctrine_Dbal_DefaultConnectionService()) && false ?: '_'}, []);
