<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'netzmacht.contao_toolkit.contao_services_factory' shared service.

return $this->services['netzmacht.contao_toolkit.contao_services_factory'] = new \Netzmacht\Contao\Toolkit\Bundle\DependencyInjection\ContaoServicesFactory(${($_ = isset($this->services['contao.framework']) ? $this->services['contao.framework'] : $this->getContao_FrameworkService()) && false ?: '_'});
