<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'netzmacht.contao_toolkit.contao.backend_user' shared service.

return $this->services['netzmacht.contao_toolkit.contao.backend_user'] = ${($_ = isset($this->services['netzmacht.contao_toolkit.contao_services_factory']) ? $this->services['netzmacht.contao_toolkit.contao_services_factory'] : $this->load('getNetzmacht_ContaoToolkit_ContaoServicesFactoryService.php')) && false ?: '_'}->createBackendUserInstance();
