<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_security.csp_report.log_formatter' shared service.

return $this->services['nelmio_security.csp_report.log_formatter'] = new \Nelmio\SecurityBundle\ContentSecurityPolicy\Violation\Log\LogFormatter();
