<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'netzmacht.contao_toolkit.listeners.set_operation_data_attribute' shared service.

return $this->services['netzmacht.contao_toolkit.listeners.set_operation_data_attribute'] = new \Netzmacht\Contao\Toolkit\Dca\Listener\SetOperationDataAttributeListener(${($_ = isset($this->services['netzmacht.contao_toolkit.dca.manager']) ? $this->services['netzmacht.contao_toolkit.dca.manager'] : $this->load('getNetzmacht_ContaoToolkit_Dca_ManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['netzmacht.contao_toolkit.routing.scope_matcher']) ? $this->services['netzmacht.contao_toolkit.routing.scope_matcher'] : $this->load('getNetzmacht_ContaoToolkit_Routing_ScopeMatcherService.php')) && false ?: '_'});
