<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ContaoBootstrap\Grid\Listener\Hook\NewsGridListener' shared service.

return $this->services['ContaoBootstrap\\Grid\\Listener\\Hook\\NewsGridListener'] = new \ContaoBootstrap\Grid\Listener\Hook\NewsGridListener(${($_ = isset($this->services['contao_bootstrap.grid.grid_provider']) ? $this->services['contao_bootstrap.grid.grid_provider'] : $this->load('getContaoBootstrap_Grid_GridProviderService.php')) && false ?: '_'});
