<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Netzmacht\Contao\Toolkit\Dca\Listener\Wizard\PagePickerListener' shared service.

return $this->services['Netzmacht\\Contao\\Toolkit\\Dca\\Listener\\Wizard\\PagePickerListener'] = new \Netzmacht\Contao\Toolkit\Dca\Listener\Wizard\PagePickerListener(${($_ = isset($this->services['templating']) ? $this->services['templating'] : $this->load('getTemplatingService.php')) && false ?: '_'}, ${($_ = isset($this->services['cca.translator.backport45translator']) ? $this->services['cca.translator.backport45translator'] : $this->getCca_Translator_Backport45translatorService()) && false ?: '_'}, ${($_ = isset($this->services['netzmacht.contao_toolkit.dca.manager']) ? $this->services['netzmacht.contao_toolkit.dca.manager'] : $this->load('getNetzmacht_ContaoToolkit_Dca_ManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['netzmacht.contao_toolkit.contao.input_adapter']) ? $this->services['netzmacht.contao_toolkit.contao.input_adapter'] : $this->load('getNetzmacht_ContaoToolkit_Contao_InputAdapterService.php')) && false ?: '_'});
