<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'translation.warmer' shared service.

return $this->services['translation.warmer'] = new \Symfony\Bundle\FrameworkBundle\CacheWarmer\TranslationsCacheWarmer((new \Symfony\Component\DependencyInjection\ServiceLocator(['translator' => function () {
    return ${($_ = isset($this->services['cca.translator.backport45translator']) ? $this->services['cca.translator.backport45translator'] : $this->getCca_Translator_Backport45translatorService()) && false ?: '_'};
}]))->withContext('translation.warmer', $this));
