<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'theme_helper.listener.insert_tags' shared service.

return $this->services['theme_helper.listener.insert_tags'] = new \Pdir\ThemeHelperBundle\EventListener\InsertTagsListener(${($_ = isset($this->services['contao.framework']) ? $this->services['contao.framework'] : $this->getContao_FrameworkService()) && false ?: '_'});
