<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'cca.translator.contao_translator' shared service.

return $this->services['cca.translator.contao_translator'] = ${($_ = isset($this->services['ContaoCommunityAlliance\\Translator\\Contao\\ContaoTranslatorFactory']) ? $this->services['ContaoCommunityAlliance\\Translator\\Contao\\ContaoTranslatorFactory'] : $this->load('getContaoTranslatorFactoryService.php')) && false ?: '_'}->createService();
