<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.command.version' shared service.

return $this->services['contao.command.version'] = new \Contao\CoreBundle\Command\VersionCommand($this->parameters['kernel.packages']);
