<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.image.picture_factory' shared service.

return $this->services['contao.image.picture_factory'] = new \Contao\CoreBundle\Image\PictureFactory(${($_ = isset($this->services['contao.image.picture_generator']) ? $this->services['contao.image.picture_generator'] : $this->load('getContao_Image_PictureGeneratorService.php')) && false ?: '_'}, ${($_ = isset($this->services['contao.image.image_factory']) ? $this->services['contao.image.image_factory'] : $this->load('getContao_Image_ImageFactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['contao.framework']) ? $this->services['contao.framework'] : $this->getContao_FrameworkService()) && false ?: '_'}, false, $this->parameters['contao.image.imagine_options']);
