<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'cca.legacy_dic.initializer' shared service.

return $this->services['cca.legacy_dic.initializer'] = new \DependencyInjection\Container\ContainerInitializer();
