<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.routing.frontend_loader' shared service.

return $this->services['contao.routing.frontend_loader'] = new \Contao\CoreBundle\Routing\FrontendLoader(false);
