<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao_bootstrap.grid.response_tagger' shared service.

return $this->services['contao_bootstrap.grid.response_tagger'] = new \Netzmacht\Contao\Toolkit\Response\NoOpResponseTagger();
