<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao_bootstrap.grid.listeners.dca.grid' shared service.

return $this->services['contao_bootstrap.grid.listeners.dca.grid'] = new \ContaoBootstrap\Grid\Listener\Dca\GridListener(${($_ = isset($this->services['contao_bootstrap.environment']) ? $this->services['contao_bootstrap.environment'] : $this->load('getContaoBootstrap_EnvironmentService.php')) && false ?: '_'});
