<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ContaoBootstrap\Grid\Listener\Dca\ContentFixParentRelationListener' shared service.

return $this->services['ContaoBootstrap\\Grid\\Listener\\Dca\\ContentFixParentRelationListener'] = new \ContaoBootstrap\Grid\Listener\Dca\ContentFixParentRelationListener(${($_ = isset($this->services['netzmacht.contao_toolkit.repository_manager']) ? $this->services['netzmacht.contao_toolkit.repository_manager'] : $this->load('getNetzmacht_ContaoToolkit_RepositoryManagerService.php')) && false ?: '_'});
