<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'cca.meta_palettes.listener.build_palettes_listener' shared service.

return $this->services['cca.meta_palettes.listener.build_palettes_listener'] = new \ContaoCommunityAlliance\MetaPalettes\Listener\BuildPalettesListener(${($_ = isset($this->services['cca.meta_palettes.parser']) ? $this->services['cca.meta_palettes.parser'] : ($this->services['cca.meta_palettes.parser'] = new \ContaoCommunityAlliance\MetaPalettes\Parser\MetaPaletteParser())) && false ?: '_'}, new \ContaoCommunityAlliance\MetaPalettes\Parser\Interpreter\StringPalettesInterpreter());
