<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao_bootstrap.core.listener.hook_listener' shared service.

return $this->services['contao_bootstrap.core.listener.hook_listener'] = new \ContaoBootstrap\Core\Listener\HookListener(${($_ = isset($this->services['event_dispatcher']) ? $this->services['event_dispatcher'] : $this->getEventDispatcherService()) && false ?: '_'}, ${($_ = isset($this->services['contao_bootstrap.environment']) ? $this->services['contao_bootstrap.environment'] : $this->load('getContaoBootstrap_EnvironmentService.php')) && false ?: '_'});
