<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao_bootstrap.core.helper.color_rotate' shared service.

return $this->services['contao_bootstrap.core.helper.color_rotate'] = new \ContaoBootstrap\Core\Helper\ColorRotate();
