<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.listener.initialize_application' shared service.

$this->services['contao.listener.initialize_application'] = $instance = new \Contao\InstallationBundle\EventListener\InitializeApplicationListener();

$instance->setContainer($this);

return $instance;
