<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ContaoCommunityAlliance\Translator\Contao\ContaoTranslatorFactory' shared service.

return $this->services['ContaoCommunityAlliance\\Translator\\Contao\\ContaoTranslatorFactory'] = new \ContaoCommunityAlliance\Translator\Contao\ContaoTranslatorFactory(${($_ = isset($this->services['event_dispatcher']) ? $this->services['event_dispatcher'] : $this->getEventDispatcherService()) && false ?: '_'});
