<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Lexik\Bundle\MaintenanceBundle\Command\DriverUnlockCommand' shared service.

return $this->services['Lexik\\Bundle\\MaintenanceBundle\\Command\\DriverUnlockCommand'] = new \Lexik\Bundle\MaintenanceBundle\Command\DriverUnlockCommand();
