<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'MenAtWork\MultiColumnWizardBundle\EventListener\Mcw\GetOptionsBridge' shared service.

return $this->services['MenAtWork\\MultiColumnWizardBundle\\EventListener\\Mcw\\GetOptionsBridge'] = new \MenAtWork\MultiColumnWizardBundle\EventListener\Mcw\GetOptionsBridge(${($_ = isset($this->services['event_dispatcher']) ? $this->services['event_dispatcher'] : $this->getEventDispatcherService()) && false ?: '_'});
