<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'MenAtWork\MultiColumnWizardBundle\EventListener\Contao\InitializeSystem' shared service.

return $this->services['MenAtWork\\MultiColumnWizardBundle\\EventListener\\Contao\\InitializeSystem'] = new \MenAtWork\MultiColumnWizardBundle\EventListener\Contao\InitializeSystem();
