<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ContaoBootstrap\Grid\Migration\MigrateAutoGridWidths' shared service.

return $this->services['ContaoBootstrap\\Grid\\Migration\\MigrateAutoGridWidths'] = new \ContaoBootstrap\Grid\Migration\MigrateAutoGridWidths(${($_ = isset($this->services['doctrine.dbal.default_connection']) ? $this->services['doctrine.dbal.default_connection'] : $this->getDoctrine_Dbal_DefaultConnectionService()) && false ?: '_'});
