<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'netzmacht.contao_toolkit.component.frontend_module_factory' shared service.

return $this->services['netzmacht.contao_toolkit.component.frontend_module_factory'] = new \Netzmacht\Contao\Toolkit\Component\ToolkitComponentFactory([0 => ${($_ = isset($this->services['ContaoBootstrap\\Grid\\Component\\Module\\GridModuleFactory']) ? $this->services['ContaoBootstrap\\Grid\\Component\\Module\\GridModuleFactory'] : $this->load('getGridModuleFactoryService.php')) && false ?: '_'}]);
