<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'netzmacht.contao_toolkit.callback_invoker' shared service.

return $this->services['netzmacht.contao_toolkit.callback_invoker'] = new \Netzmacht\Contao\Toolkit\Callback\Invoker(${($_ = isset($this->services['netzmacht.contao_toolkit.contao_services_factory']) ? $this->services['netzmacht.contao_toolkit.contao_services_factory'] : $this->load('getNetzmacht_ContaoToolkit_ContaoServicesFactoryService.php')) && false ?: '_'}->createSystemAdapter());
