<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'netzmacht.contao_toolkit.listeners.get_template_helpers' shared service.

return $this->services['netzmacht.contao_toolkit.listeners.get_template_helpers'] = new \Netzmacht\Contao\Toolkit\View\Template\Subscriber\GetTemplateHelpersListener((new \Netzmacht\Contao\Toolkit\View\Assets\GlobalsAssetsManagerFactory(false))->create(), ${($_ = isset($this->services['cca.translator.backport45translator']) ? $this->services['cca.translator.backport45translator'] : $this->getCca_Translator_Backport45translatorService()) && false ?: '_'});
