<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ContaoBootstrap\Grid\Listener\Dca\ParentFixContentParentRelationsListener' shared service.

return $this->services['ContaoBootstrap\\Grid\\Listener\\Dca\\ParentFixContentParentRelationsListener'] = new \ContaoBootstrap\Grid\Listener\Dca\ParentFixContentParentRelationsListener(${($_ = isset($this->services['doctrine.dbal.default_connection']) ? $this->services['doctrine.dbal.default_connection'] : $this->getDoctrine_Dbal_DefaultConnectionService()) && false ?: '_'}, ${($_ = isset($this->services['netzmacht.contao_toolkit.dca.manager']) ? $this->services['netzmacht.contao_toolkit.dca.manager'] : $this->load('getNetzmacht_ContaoToolkit_Dca_ManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['netzmacht.contao_toolkit.repository_manager']) ? $this->services['netzmacht.contao_toolkit.repository_manager'] : $this->load('getNetzmacht_ContaoToolkit_RepositoryManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['netzmacht.contao_toolkit.contao.input_adapter']) ? $this->services['netzmacht.contao_toolkit.contao.input_adapter'] : $this->load('getNetzmacht_ContaoToolkit_Contao_InputAdapterService.php')) && false ?: '_'});
