<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Netzmacht\Contao\Toolkit\Dca\Listener\Button\StateButtonCallbackListener' shared service.

$a = ${($_ = isset($this->services['netzmacht.contao_toolkit.dca.manager']) ? $this->services['netzmacht.contao_toolkit.dca.manager'] : $this->load('getNetzmacht_ContaoToolkit_Dca_ManagerService.php')) && false ?: '_'};

return $this->services['Netzmacht\\Contao\\Toolkit\\Dca\\Listener\\Button\\StateButtonCallbackListener'] = new \Netzmacht\Contao\Toolkit\Dca\Listener\Button\StateButtonCallbackListener(${($_ = isset($this->services['netzmacht.contao_toolkit.contao_services_factory']) ? $this->services['netzmacht.contao_toolkit.contao_services_factory'] : $this->load('getNetzmacht_ContaoToolkit_ContaoServicesFactoryService.php')) && false ?: '_'}->createBackendAdapter(), ${($_ = isset($this->services['netzmacht.contao_toolkit.contao.input_adapter']) ? $this->services['netzmacht.contao_toolkit.contao.input_adapter'] : $this->load('getNetzmacht_ContaoToolkit_Contao_InputAdapterService.php')) && false ?: '_'}, new \Netzmacht\Contao\Toolkit\Data\Updater\DatabaseRowUpdater(${($_ = isset($this->services['netzmacht.contao_toolkit.contao.backend_user']) ? $this->services['netzmacht.contao_toolkit.contao.backend_user'] : $this->load('getNetzmacht_ContaoToolkit_Contao_BackendUserService.php')) && false ?: '_'}, ${($_ = isset($this->services['doctrine.dbal.default_connection']) ? $this->services['doctrine.dbal.default_connection'] : $this->getDoctrine_Dbal_DefaultConnectionService()) && false ?: '_'}, $a, ${($_ = isset($this->services['netzmacht.contao_toolkit.callback_invoker']) ? $this->services['netzmacht.contao_toolkit.callback_invoker'] : $this->load('getNetzmacht_ContaoToolkit_CallbackInvokerService.php')) && false ?: '_'}), $a);
