<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'DependencyInjection\Container\ContaoServices\ServiceFactory' shared service.

return $this->services['DependencyInjection\\Container\\ContaoServices\\ServiceFactory'] = new \DependencyInjection\Container\ContaoServices\ServiceFactory($this);
