<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'terminal42_folderpage.listener.page_status_icon' shared service.

return $this->services['terminal42_folderpage.listener.page_status_icon'] = new \Terminal42\FolderpageBundle\EventListener\PageStatusIconListener();
