<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'MenAtWork\MultiColumnWizardBundle\EventListener\DcGeneral\UpdateDataDefinition' shared service.

return $this->services['MenAtWork\\MultiColumnWizardBundle\\EventListener\\DcGeneral\\UpdateDataDefinition'] = new \MenAtWork\MultiColumnWizardBundle\EventListener\DcGeneral\UpdateDataDefinition();
