<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao_bootstrap.grid.view.renderer_helper' shared service.

@trigger_error('Service \'contao_bootstrap.grid.view.renderer_helper\' will be removed in one of the next minor releases! Only for internal code transition.', E_USER_DEPRECATED);

return $this->services['contao_bootstrap.grid.view.renderer_helper'] = new \ContaoBootstrap\Grid\View\ComponentRenderHelper(${($_ = isset($this->services['contao_bootstrap.grid.grid_provider']) ? $this->services['contao_bootstrap.grid.grid_provider'] : $this->load('getContaoBootstrap_Grid_GridProviderService.php')) && false ?: '_'}, ${($_ = isset($this->services['netzmacht.contao_toolkit.routing.scope_matcher']) ? $this->services['netzmacht.contao_toolkit.routing.scope_matcher'] : $this->load('getNetzmacht_ContaoToolkit_Routing_ScopeMatcherService.php')) && false ?: '_'}, ${($_ = isset($this->services['contao_bootstrap.core.helper.color_rotate']) ? $this->services['contao_bootstrap.core.helper.color_rotate'] : ($this->services['contao_bootstrap.core.helper.color_rotate'] = new \ContaoBootstrap\Core\Helper\ColorRotate())) && false ?: '_'});
