<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.cache' shared service.

return $this->services['contao.cache'] = new \Doctrine\Common\Cache\FilesystemCache(($this->targetDirs[0].'/contao/cache'), '', 18);
