<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.image.picture_generator' shared service.

return $this->services['contao.image.picture_generator'] = new \Contao\Image\PictureGenerator(${($_ = isset($this->services['contao.image.resizer']) ? $this->services['contao.image.resizer'] : $this->load('getContao_Image_ResizerService.php')) && false ?: '_'});
