<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.image.image_factory' shared service.

return $this->services['contao.image.image_factory'] = new \Contao\CoreBundle\Image\ImageFactory(${($_ = isset($this->services['contao.image.resizer']) ? $this->services['contao.image.resizer'] : $this->load('getContao_Image_ResizerService.php')) && false ?: '_'}, ${($_ = isset($this->services['contao.image.imagine']) ? $this->services['contao.image.imagine'] : ($this->services['contao.image.imagine'] = new \Imagine\Gd\Imagine())) && false ?: '_'}, ${($_ = isset($this->services['contao.image.imagine_svg']) ? $this->services['contao.image.imagine_svg'] : ($this->services['contao.image.imagine_svg'] = new \Contao\ImagineSvg\Imagine())) && false ?: '_'}, ${($_ = isset($this->services['filesystem']) ? $this->services['filesystem'] : ($this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem())) && false ?: '_'}, ${($_ = isset($this->services['contao.framework']) ? $this->services['contao.framework'] : $this->getContao_FrameworkService()) && false ?: '_'}, true, $this->parameters['contao.image.imagine_options'], $this->parameters['contao.image.valid_extensions']);
