<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao_installation.command.lock' shared service.

return $this->services['contao_installation.command.lock'] = new \Contao\InstallationBundle\Command\LockCommand(($this->targetDirs[2].'/install_lock'));
