<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.picker.builder' shared service.

$this->services['contao.picker.builder'] = $instance = new \Contao\CoreBundle\Picker\PickerBuilder(${($_ = isset($this->services['knp_menu.factory']) ? $this->services['knp_menu.factory'] : $this->load('getKnpMenu_FactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});

$instance->addProvider(${($_ = isset($this->services['contao.picker.page_provider']) ? $this->services['contao.picker.page_provider'] : $this->load('getContao_Picker_PageProviderService.php')) && false ?: '_'});
$instance->addProvider(${($_ = isset($this->services['contao.picker.file_provider']) ? $this->services['contao.picker.file_provider'] : $this->load('getContao_Picker_FileProviderService.php')) && false ?: '_'});
$instance->addProvider(${($_ = isset($this->services['contao_news.picker.news_provider']) ? $this->services['contao_news.picker.news_provider'] : $this->load('getContaoNews_Picker_NewsProviderService.php')) && false ?: '_'});
$instance->addProvider(${($_ = isset($this->services['contao_calendar.picker.event_provider']) ? $this->services['contao_calendar.picker.event_provider'] : $this->load('getContaoCalendar_Picker_EventProviderService.php')) && false ?: '_'});
$instance->addProvider(${($_ = isset($this->services['contao_faq.picker.faq_provider']) ? $this->services['contao_faq.picker.faq_provider'] : $this->load('getContaoFaq_Picker_FaqProviderService.php')) && false ?: '_'});
$instance->addProvider(${($_ = isset($this->services['contao.picker.article_provider']) ? $this->services['contao.picker.article_provider'] : $this->load('getContao_Picker_ArticleProviderService.php')) && false ?: '_'});

return $instance;
