<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao_bootstrap.grid.listeners.theme_export' shared service.

return $this->services['contao_bootstrap.grid.listeners.theme_export'] = new \ContaoBootstrap\Grid\Listener\ThemeExportListener(${($_ = isset($this->services['contao.framework']) ? $this->services['contao.framework'] : $this->getContao_FrameworkService()) && false ?: '_'});
