<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.listener.response_exception' shared service.

return $this->services['contao.listener.response_exception'] = new \Contao\CoreBundle\EventListener\ResponseExceptionListener();
