<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'netzmacht.contao_toolkit.listeners.register_component_decorators' shared service.

return $this->services['netzmacht.contao_toolkit.listeners.register_component_decorators'] = new \Netzmacht\Contao\Toolkit\Bundle\DependencyInjection\Listener\RegisterComponentDecoratorsListener(['miscellaneous' => [0 => 'bs_grid']], ['bs_grid' => [0 => 'bs_gridStart', 1 => 'bs_gridSeparator', 2 => 'bs_gridStop'], 'media' => [0 => 'bs_grid_gallery']]);
