<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_security.csp_report.logger' shared service.

return $this->services['nelmio_security.csp_report.logger'] = new \Nelmio\SecurityBundle\ContentSecurityPolicy\Violation\Log\Logger(${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->getLoggerService()) && false ?: '_'}, ${($_ = isset($this->services['nelmio_security.csp_report.log_formatter']) ? $this->services['nelmio_security.csp_report.log_formatter'] : ($this->services['nelmio_security.csp_report.log_formatter'] = new \Nelmio\SecurityBundle\ContentSecurityPolicy\Violation\Log\LogFormatter())) && false ?: '_'}, 'notice');
