<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'netzmacht.contao_toolkit.listeners.merge_hook_listeners' shared service.

return $this->services['netzmacht.contao_toolkit.listeners.merge_hook_listeners'] = new \Netzmacht\Contao\Toolkit\Bundle\DependencyInjection\Listener\MergeHookListenersListener(${($_ = isset($this->services['netzmacht.contao_toolkit.callback_invoker']) ? $this->services['netzmacht.contao_toolkit.callback_invoker'] : $this->load('getNetzmacht_ContaoToolkit_CallbackInvokerService.php')) && false ?: '_'}, ['initializeSystem' => [100 => [0 => [0 => 'netzmacht.contao_toolkit.listeners.register_component_decorators', 1 => 'onInitializeSystem'], 1 => [0 => 'netzmacht.contao_toolkit.listeners.register_models', 1 => 'onInitializeSystem']]], 'loadDataContainer' => [0 => [0 => [0 => 'netzmacht.contao_toolkit.listeners.set_operation_data_attribute', 1 => 'onLoadDataContainer']]]]);
