<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'netzmacht.contao_toolkit.listeners.create_formatter_subscriber' shared service.

$a = ${($_ = isset($this->services['netzmacht.contao_toolkit.contao_services_factory']) ? $this->services['netzmacht.contao_toolkit.contao_services_factory'] : $this->load('getNetzmacht_ContaoToolkit_ContaoServicesFactoryService.php')) && false ?: '_'};
$b = new \Netzmacht\Contao\Toolkit\Dca\Formatter\Value\OptionsFormatter(${($_ = isset($this->services['netzmacht.contao_toolkit.callback_invoker']) ? $this->services['netzmacht.contao_toolkit.callback_invoker'] : $this->load('getNetzmacht_ContaoToolkit_CallbackInvokerService.php')) && false ?: '_'});

return $this->services['netzmacht.contao_toolkit.listeners.create_formatter_subscriber'] = new \Netzmacht\Contao\Toolkit\Dca\Formatter\Subscriber\CreateFormatterSubscriber([0 => new \Netzmacht\Contao\Toolkit\Dca\Formatter\Value\ForeignKeyFormatter(${($_ = isset($this->services['doctrine.dbal.default_connection']) ? $this->services['doctrine.dbal.default_connection'] : $this->getDoctrine_Dbal_DefaultConnectionService()) && false ?: '_'}), 1 => new \Netzmacht\Contao\Toolkit\Dca\Formatter\Value\FileUuidFormatter(), 2 => new \Netzmacht\Contao\Toolkit\Dca\Formatter\Value\DateFormatter($a->createConfigAdapter()), 3 => new \Netzmacht\Contao\Toolkit\Dca\Formatter\Value\HtmlFormatter(), 4 => new \Netzmacht\Contao\Toolkit\Dca\Formatter\Value\ReferenceFormatter(), 5 => $b], [0 => new \Netzmacht\Contao\Toolkit\Dca\Formatter\Value\HiddenValueFormatter(), 1 => new \Netzmacht\Contao\Toolkit\Dca\Formatter\Value\DeserializeFormatter(), 2 => new \Netzmacht\Contao\Toolkit\Dca\Formatter\Value\EncryptedFormatter($a->createEncryptionAdapter())], [0 => new \Netzmacht\Contao\Toolkit\Dca\Formatter\Value\FlattenFormatter()], $b);
