<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'nelmio_security.csp_reporter_controller' shared service.

$a = new \Nelmio\SecurityBundle\ContentSecurityPolicy\Violation\Filter\Filter();
$a->addNoiseDetector(new \Nelmio\SecurityBundle\ContentSecurityPolicy\Violation\Filter\DomainsNoiseDetector());
$a->addNoiseDetector(new \Nelmio\SecurityBundle\ContentSecurityPolicy\Violation\Filter\DomainsRegexNoiseDetector());
$a->addNoiseDetector(new \Nelmio\SecurityBundle\ContentSecurityPolicy\Violation\Filter\SchemesNoiseDetector());
$a->addNoiseDetector(new \Nelmio\SecurityBundle\ContentSecurityPolicy\Violation\Filter\InjectedScriptsNoiseDetector());
$a->addNoiseDetector(new \Nelmio\SecurityBundle\ContentSecurityPolicy\Violation\Filter\BrowserBugsNoiseDetector(${($_ = isset($this->services['nelmio_security.ua_parser.ua_php.provider']) ? $this->services['nelmio_security.ua_parser.ua_php.provider'] : $this->load('getNelmioSecurity_UaParser_UaPhp_ProviderService.php')) && false ?: '_'}));

return $this->services['nelmio_security.csp_reporter_controller'] = new \Nelmio\SecurityBundle\Controller\ContentSecurityPolicyController(${($_ = isset($this->services['nelmio_security.csp_report.logger']) ? $this->services['nelmio_security.csp_report.logger'] : $this->load('getNelmioSecurity_CspReport_LoggerService.php')) && false ?: '_'}, ${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'}, $a);
