<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'terminal42.header_replay.header_replay_stop_propagation_listener' shared service.

return $this->services['terminal42.header_replay.header_replay_stop_propagation_listener'] = new \Terminal42\HeaderReplay\EventListener\HeaderReplayStopPropagationListener(${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'});
