<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao_manager.command.install_web_dir' shared service.

return $this->services['contao_manager.command.install_web_dir'] = new \Contao\ManagerBundle\Command\InstallWebDirCommand($this->targetDirs[3]);
