<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao_installation.command.unlock' shared service.

return $this->services['contao_installation.command.unlock'] = new \Contao\InstallationBundle\Command\UnlockCommand(($this->targetDirs[2].'/install_lock'));
