<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao_bootstrap.grid.grid_builder' shared service.

return $this->services['contao_bootstrap.grid.grid_builder'] = new \ContaoBootstrap\Grid\GridBuilder();
