<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.resource_locator' shared service.

return $this->services['contao.resource_locator'] = new \Symfony\Component\Config\FileLocator($this->getParameter('contao.resources_paths'));
