<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.install_tool_twig_extension' shared service.

return $this->services['contao.install_tool_twig_extension'] = new \SensioLabs\AnsiConverter\Bridge\Twig\AnsiExtension();
