<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.controller.insert_tags' shared service.

$this->services['contao.controller.insert_tags'] = $instance = new \Contao\CoreBundle\Controller\InsertTagsController(${($_ = isset($this->services['contao.framework']) ? $this->services['contao.framework'] : $this->getContao_FrameworkService()) && false ?: '_'});

$instance->setContainer($this);

return $instance;
