<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao_bootstrap.grid.listeners.dca.content' shared service.

return $this->services['contao_bootstrap.grid.listeners.dca.content'] = new \ContaoBootstrap\Grid\Listener\Dca\ContentListener(${($_ = isset($this->services['contao_bootstrap.environment']) ? $this->services['contao_bootstrap.environment'] : $this->load('getContaoBootstrap_EnvironmentService.php')) && false ?: '_'}, ${($_ = isset($this->services['doctrine.dbal.default_connection']) ? $this->services['doctrine.dbal.default_connection'] : $this->getDoctrine_Dbal_DefaultConnectionService()) && false ?: '_'}, ${($_ = isset($this->services['contao.framework']) ? $this->services['contao.framework'] : $this->getContao_FrameworkService()) && false ?: '_'}, ${($_ = isset($this->services['contao.image.image_sizes']) ? $this->services['contao.image.image_sizes'] : $this->load('getContao_Image_ImageSizesService.php')) && false ?: '_'}, ${($_ = isset($this->services['netzmacht.contao_toolkit.contao.backend_user']) ? $this->services['netzmacht.contao_toolkit.contao.backend_user'] : $this->load('getNetzmacht_ContaoToolkit_Contao_BackendUserService.php')) && false ?: '_'});
