<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ContaoBootstrap\Grid\Component\ContentElement\GalleryFactory' shared service.

return $this->services['ContaoBootstrap\\Grid\\Component\\ContentElement\\GalleryFactory'] = new \ContaoBootstrap\Grid\Component\ContentElement\GalleryFactory(${($_ = isset($this->services['templating']) ? $this->services['templating'] : $this->load('getTemplatingService.php')) && false ?: '_'}, ${($_ = isset($this->services['contao_bootstrap.grid.grid_provider']) ? $this->services['contao_bootstrap.grid.grid_provider'] : $this->load('getContaoBootstrap_Grid_GridProviderService.php')) && false ?: '_'}, ${($_ = isset($this->services['netzmacht.contao_toolkit.contao_services_factory']) ? $this->services['netzmacht.contao_toolkit.contao_services_factory'] : $this->load('getNetzmacht_ContaoToolkit_ContaoServicesFactoryService.php')) && false ?: '_'}->createFrontendUserInstance(), ${($_ = isset($this->services['contao_bootstrap.grid.response_tagger']) ? $this->services['contao_bootstrap.grid.response_tagger'] : ($this->services['contao_bootstrap.grid.response_tagger'] = new \Netzmacht\Contao\Toolkit\Response\NoOpResponseTagger())) && false ?: '_'});
