<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ContaoBootstrap\Grid\Component\Module\GridModuleFactory' shared service.

return $this->services['ContaoBootstrap\\Grid\\Component\\Module\\GridModuleFactory'] = new \ContaoBootstrap\Grid\Component\Module\GridModuleFactory(${($_ = isset($this->services['templating']) ? $this->services['templating'] : $this->load('getTemplatingService.php')) && false ?: '_'}, ${($_ = isset($this->services['netzmacht.contao_toolkit.translation.translator']) ? $this->services['netzmacht.contao_toolkit.translation.translator'] : $this->getNetzmacht_ContaoToolkit_Translation_TranslatorService()) && false ?: '_'}, ${($_ = isset($this->services['contao_bootstrap.grid.grid_provider']) ? $this->services['contao_bootstrap.grid.grid_provider'] : $this->load('getContaoBootstrap_Grid_GridProviderService.php')) && false ?: '_'}, ${($_ = isset($this->services['contao_bootstrap.grid.response_tagger']) ? $this->services['contao_bootstrap.grid.response_tagger'] : ($this->services['contao_bootstrap.grid.response_tagger'] = new \Netzmacht\Contao\Toolkit\Response\NoOpResponseTagger())) && false ?: '_'});
