<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_security.ua_parser.ua_php.provider' shared service.

return $this->services['nelmio_security.ua_parser.ua_php.provider'] = \UAParser\Parser::create();
