<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'netzmacht.contao_toolkit.dca.manager' shared service.

return $this->services['netzmacht.contao_toolkit.dca.manager'] = new \Netzmacht\Contao\Toolkit\Dca\Manager(new \Netzmacht\Contao\Toolkit\Dca\DcaLoader(), new \Netzmacht\Contao\Toolkit\Dca\Formatter\FormatterFactory(${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'}));
