<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'nelmio_security.ua_parser.ua_php' shared service.

return $this->services['nelmio_security.ua_parser.ua_php'] = new \Nelmio\SecurityBundle\UserAgent\UAFamilyParser\UAFamilyParser(${($_ = isset($this->services['nelmio_security.ua_parser.ua_php.provider']) ? $this->services['nelmio_security.ua_parser.ua_php.provider'] : $this->load('getNelmioSecurity_UaParser_UaPhp_ProviderService.php')) && false ?: '_'});
