<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.authentication.manager' shared service.

$this->services['security.authentication.manager'] = $instance = new \Symfony\Component\Security\Core\Authentication\AuthenticationProviderManager(new RewindableGenerator(function () {
    yield 0 => ${($_ = isset($this->services['security.authentication.provider.simple_preauth.backend']) ? $this->services['security.authentication.provider.simple_preauth.backend'] : $this->load('getSecurity_Authentication_Provider_SimplePreauth_BackendService.php')) && false ?: '_'};
    yield 1 => ${($_ = isset($this->services['security.authentication.provider.simple_preauth.frontend']) ? $this->services['security.authentication.provider.simple_preauth.frontend'] : $this->load('getSecurity_Authentication_Provider_SimplePreauth_FrontendService.php')) && false ?: '_'};
}, 2), true);

$instance->setEventDispatcher(${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'});

return $instance;
