<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK62ulpo\appürodDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK62ulpo/appürodDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerK62ulpo.legacy');

    return;
}

if (!\class_exists(appürodDebugProjectContainer::class, false)) {
    \class_alias(\ContainerK62ulpo\appürodDebugProjectContainer::class, appürodDebugProjectContainer::class, false);
}

return new \ContainerK62ulpo\appürodDebugProjectContainer([
    'container.build_hash' => 'K62ulpo',
    'container.build_id' => 'b1df6449',
    'container.build_time' => 1572938376,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK62ulpo');
