<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR93565n\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR93565n/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerR93565n.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerR93565n\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerR93565n\appProdProjectContainer([
    'container.build_hash' => 'R93565n',
    'container.build_id' => '03e14e14',
    'container.build_time' => 1583054936,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR93565n');
