<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMmiijsn\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMmiijsn/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerMmiijsn.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerMmiijsn\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerMmiijsn\appProdProjectContainer([
    'container.build_hash' => 'Mmiijsn',
    'container.build_id' => '107804da',
    'container.build_time' => 1583080133,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMmiijsn');
